apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: minio-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeName: minio-pv
