controller:
  # 커뮤니티용 - kubernetes/ingress-nginx
  image:
    registry: registry.k8s.io
    image: ingress-nginx/controller
    tag: "v4.14.1"

  # Service에 externalIPs 속성 추가
  service:
    type: ClusterIP
    externalIPs:
      - 40.0.0.141

  # Nginx 설치시 ingressClass 생성
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"
  ingressClass: nginx

  extraEnvs:
    - name: TZ
      value: Asia/Seoul

  replicaCount: 1

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi

  # 프로메테우스 메트릭 수집 설정
  metrics:
    enabled: true
    serviceMonitor:
      enabled:
        true
        #      namespace: monitoring
        #      additionalLabels:
        #        release: monitoring
